### ISSUE TITLE
Will not pull Access token and complete the initial Aunthentication

### ISSUE THREAD

**Issue by swheeler911** [mbegan/Box-PSModule#1]
Hey Matt,

This module is very intriguing and seems as though it will do the job of renewing the access token properly.

In testing it, I am receiving a stop error at line 300 on  box.psm1 (the :"Throw" just under the $Refresh)
I have gone over a few different scenarios and cannot seem to figure it out. Here is the actual error, perhaps you can shed some light on it for me?:

Invalid JSON primitive: Action.
At C:\windows\system32\windowspowershell\v1.0\Modules\Box\box.psm1:300 char:9
-         throw($_.Exception.Message)
-         ~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : OperationStopped: (Invalid JSON primitive: Action.:String) [], RuntimeException
  - FullyQualifiedErrorId : Invalid JSON primitive: Action.

**Comment by mbegan** [comment]
Hi @swheeler911 
Can you provide the output from $PSVersionTable i'd like to compare versions.

The location that the error is being thrown from is a step or two away from where i suspect real error is occurring.  Can you provide the output from $Error[1]  $Error[2] and $Error[3] directly after encountering the error.  This will provide a little additional context.

**Comment by swheeler911** [comment]
here is the output:

Name                           Value

---

PSVersion                      5.0.10240.16384
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   10.0.10240.16384
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3

On Tue, Apr 12, 2016 at 2:32 PM, Matt Egan notifications@github.com wrote:

> Hi @swheeler911 https://github.com/swheeler911
> Can you provide the output from $PSVersionTable i'd like to compare
> versions.
> 
> The location that the error is being thrown from is a step or two away
> from where i suspect real error is occurring. Can you provide the output
> from $Error[1] $Error[2] and $Error[3] directly after encountering the
> error. This will provide a little additional context.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/mbegan/Box-PSModule/issues/1#issuecomment-209068406

## 

Stephen Wheeler

swheeler911@gmail.com
(210) 367 3767

 Please consider the environment before printing this email.

**Comment by swheeler911** [comment]
Missed the second part of what you wanted. Here are the error outputs:

At C:\windows\system32\windowspowershell\v1.0\Modules\Box\box.psm1:300
char:9
-         throw($_.Exception.Message)
-         ~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : OperationStopped: (Invalid JSON primitive:
    Action.:String) [], RuntimeException
  - FullyQualifiedErrorId : Invalid JSON primitive: Action.
    ConvertFrom-Json : Invalid JSON primitive: Action.
    At C:\windows\system32\windowspowershell\v1.0\Modules\Box\box.psm1:196
    char:23
- ... rrMessage = ConvertFrom-Json ($_.ErrorDetails.Message) -ErrorAction S
  ...
-                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json],
    ArgumentException
  - FullyQualifiedErrorId :
    System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
    Invoke-RestMethod :
    Action blocked.

External web storage sites present an elevated level of risk to the
security, availability and integrity of our network.
Typically, external web storage sites do not employ the same level of
commitment to security employed here at .
The possible introduction of malicious code, such as computer viruses,
network worms, Trojan horses, and logic bombs is significant.
Not to mention the possibility of data leakage.  For this reason,
Information Security has elected to either block or limit access to these
sites.
If you still feel there is a business need to access this site,
please contact Security Advisors with your justification.

_Looks like a firewall blocking on this one, working on the firewall to see
what could be getting blocked_

At C:\windows\system32\windowspowershell\v1.0\Modules\Box\box.psm1:192
char:17
- ...     $json = Invoke-RestMethod -Uri $uri -Method Post -ContentType "ap
  ...
-                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation:
    (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
  - FullyQualifiedErrorId :
    WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
    error : The term 'error' is not recognized as the name of a cmdlet,
    function, script file, or operable program. Check the spelling of the name,
    or if a path was included, verify that the path is correct and try again.
    At line:1 char:1
- error
- ~~~~~
  - CategoryInfo          : ObjectNotFound: (error:String) [],
    CommandNotFoundException
  - FullyQualifiedErrorId : CommandNotFoundException

On Tue, Apr 12, 2016 at 2:54 PM, Steve Wheeler swheeler911@gmail.com
wrote:

> here is the output:
> 
> Name                           Value
> 
> ---
> 
> PSVersion                      5.0.10240.16384
> WSManStackVersion              3.0
> SerializationVersion           1.1.0.1
> CLRVersion                     4.0.30319.42000
> BuildVersion                   10.0.10240.16384
> PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
> PSRemotingProtocolVersion      2.3
> 
> On Tue, Apr 12, 2016 at 2:32 PM, Matt Egan notifications@github.com
> wrote:
> 
> > Hi @swheeler911 https://github.com/swheeler911
> > Can you provide the output from $PSVersionTable i'd like to compare
> > versions.
> > 
> > The location that the error is being thrown from is a step or two away
> > from where i suspect real error is occurring. Can you provide the output
> > from $Error[1] $Error[2] and $Error[3] directly after encountering the
> > error. This will provide a little additional context.
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub
> > https://github.com/mbegan/Box-PSModule/issues/1#issuecomment-209068406
> 
> ## 
> 
> Stephen Wheeler
> 
> swheeler911@gmail.com
> (210) 367 3767
> 
>  Please consider the environment before printing this email.

## 

Stephen Wheeler

swheeler911@gmail.com
(210) 367 3767

 Please consider the environment before printing this email.

**Comment by swheeler911** [comment]
If I user api.box.com to get the token it works fine, then I switch over to app.box.com, or account.box.com I get blocked by my firewall so I will have to get that taken care of. 
Ill see if this works with just using App.box.com/api but it looks like I may have to do the token request with api.box.com first. Perhaps they changed some things since you wrote the script? or being on an enterprise/SSO account it acts differently.

**Comment by mbegan** [comment]
Hi Sorry for the delayed response. I was trying to get my hands on a PS5 environment to see if that had anything to do with it, as it is my computer refuses to run the update (sigh)

Based on what you are describing I really thing it boils down to firewall or connectivity issues.

app.box.com is the hostname that was conveyed in the documentation (for oauth operations) though I think i found app and api would work interchangeably (i can't remember). NSLOOKUP shows that all 3 hostname (app, api, account) resolve a similar pool of ip addresses but who knows what they are doing with host-headers / SNI.

The environment i use it with is an enterprise/SSO environment (SSO required).

**Comment by swheeler911** [comment]
I was able to get the authentication portion working. I had to use a
separate URL in place of app.box.com. I have a dedicated url that is
unblocked at the firewall so it was able to send through the token.
I really appreciate your assistance. Just need to get the upload portion
figured out now.

On Sat, Apr 16, 2016 at 9:28 AM, Matt Egan notifications@github.com wrote:

> Hi Sorry for the delayed response. I was trying to get my hands on a PS5
> environment to see if that had anything to do with it, as it is my computer
> refuses to run the update (sigh)
> 
> Based on what you are describing I really thing it boils down to firewall
> or connectivity issues.
> 
> app.box.com is the hostname that was conveyed in the documentation (for
> oauth operations) though I think i found app and api would work
> interchangeably (i can't remember). NSLOOKUP shows that all 3 hostname
> (app, api, account) resolve a similar pool of ip addresses but who knows
> what they are doing with host-headers / SNI.
> 
> The environment i use it with is an enterprise/SSO environment (SSO
> required).
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/mbegan/Box-PSModule/issues/1#issuecomment-210825993

## 

Stephen Wheeler

swheeler911@gmail.com
(210) 367 3767

 Please consider the environment before printing this email.
