### ISSUE TITLE
Initial Issue

### ISSUE THREAD

**Issue by Buckeye888** [mbegan/Box-PSModule#4]
Thanks for the code here but I am just running into an issue right from the start. I get through all of the steps to generate the token with no errors. I do the import-module Box with no issues. I see all the commands.  When i then try to do a simple command like boxgetaliases -userID xxxx I get the red errors of:

No env by the name of: false
At C:\Program Files\WindowsPowerShell\Modules\box\box.psm1:439 char:9
+         throw ("No env by the name of: " + $name)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (No env by the name of: false:String) [], RuntimeException
    + FullyQualifiedErrorId : No env by the name of: false

What am I missing?

Thanks for the help.

**Comment by mjanow** [comment]
I got around this exact issue by manually entering the name of my app from Box Developer so mine was...
boxGetAliases -env box-ps -userID xxxxxxx
What I cannot do is use -username

**Comment by mbegan** [comment]
When running boxCreateEnv you need to specify -default if you want that env to be the default/implied env.

looking at the issue with -username, just saw another issue of the same nature.

**Comment by Buckeye888** [comment]
That worked. I also can use the -username with no issue now.

**Comment by mbegan** [comment]
Cool
