### ISSUE TITLE
Error Pulling username with boxGetUser

### ISSUE THREAD

**Issue by mjanow** [mbegan/Box-PSModule#5]
PS C:\WINDOWS\system32> boxGetUser -username anything

boxThrowError : Cannot bind argument to parameter 'text' because it is an empty string.
At C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Box\box.psm1:696 char:29
+         boxThrowError -text $txt
+                             ~~~~
    + CategoryInfo          : InvalidData: (:) [boxThrowError], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,boxThrowError

**Comment by mbegan** [comment]
need more context, looks like the real error is being hidden.
Can you run the following and share the output

```powershell
$Error.Clear()
boxGetUser -username anything
foreach ($e in $Error){$e}
```

**Comment by mjanow** [comment]
boxThrowError : Cannot bind argument to parameter 'text' because it is an empty string.
At C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Box\box.psm1:696 char:29
+         boxThrowError -text $txt
+                             ~~~~
    + CategoryInfo          : InvalidData: (:) [boxThrowError], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,boxThrowError
 
boxThrowError : Cannot bind argument to parameter 'text' because it is an empty string.
At C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Box\box.psm1:696 char:29
+         boxThrowError -text $txt
+                             ~~~~
    + CategoryInfo          : InvalidData: (:) [boxThrowError], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,boxThrowError
 
Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (403) Forbidden."
At C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Box\box.psm1:674 char:9
+         [System.Net.HttpWebResponse]$response = $request.GetResponse( ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

**Comment by mbegan** [comment]
403 forbidden, you sure your tokens are valid?  did you say in the other issue that you COULD get data based on ID?

I no longer have access to a box tenant to test with so i'm pretty limited in what i can see/do.

**Comment by mjanow** [comment]
Yes, I am able to use boxGetFolder and boxGetCurrentUser. I wonder if the Box API has changed and only accepts -userid? That will really be difficult for me to automate a process to create a specific folder in every user account from an AD Group. User ID numbers are the most ambiguous identifier compared to username or name.

**Comment by mbegan** [comment]
The cmdlet has a couple different behaviors

if you send userid it does this
https://developer.box.com/reference#users

if you send username it does this with filter_term = {username}
https://developer.box.com/reference#get-all-users-in-an-enterprise

I don't see anything that makes me think the API has changed.  I would double check the account you used to authorize the integration and makes sure it is appropriately entitled.

**Comment by mjanow** [comment]
The account I am using is the Admin account, I have no reason to explain how I can use userid and run the other functions, but I cannot have access to username. How could I rewrite the boxGetUser function to simply pull all users?

**Comment by mbegan** [comment]
As long as the user running the command has permissions the intended functionality of boxGetUser is to return ALL users when run without the username or userid parameters.

**Comment by mjanow** [comment]
So, after speaking with Box API support I found a dumb error where the original support hadn't explained the need to alter default app settings to check manage users! So, -username is working now! I do have a new issue I will open on a new thread.
